botid: 1234567890
botnickname: 樱子
version: 1.1.0

output_group: 1234567890
command_output: true

banned_groups:
  - 1234567890

super_users:
  - 1234567890

# API keys
llm:
  aliyun-apikey: sk-1234567890

pjsk_tool:
  zh_db_link: "http://a.b.c.d/zh-CN/music_titles.json"
  ja_db_link: "https://a.b.c.d/ja/music_titles.json"
  diffi_cndb_link: "https://a.b.c.d/musicDifficulties.json"
  diffi_jpdb_link: "https://a.b.c.d/musicDifficulties.json"